global:
    scrape_interval: 15s
    external_labels:
        monitor: 'my-monitor'
rule_files:
  - "rules/rules.yml"  
scrape_configs:
    - job_name: 'prometheus'
      scrape_interval: 5s
      static_configs:
          - targets: ['172.16.99.200:9090']
            
    - job_name: 'node_resources'
      scrape_interval: 10s
      static_configs:
        - targets: ['172.16.99.200:9110']
          labels:
              instance: 'Centos7-1'
    
    - job_name: pushgateway
      scrape_interval: 10s
      static_configs:
        - targets: ['172.16.99.200:9091']
          labels:
              instance: pushgateway